### PR TITLE
Update Chapter4.md

### PR DESCRIPTION
**Pull request by guncha**
Fix minor formatting issue with code blocks

### CODE REVIEW

**Comment by chriswailes** [comment]
Thanks for the help!

**Comment by guncha** [comment]
Thank you for the awesome work! I'm working through the tutorial and I'm loving it. Please let me know if you need any help with maintenance. I've noticed a few issues with LLVM bindings, mostly.

**Comment by chriswailes** [comment]
I'm glad you're enjoying the toolkit.  I'd actually appreciate it if you could send me a list of the bindings issues.  They can be complicated to keep correct :-(

**Comment by guncha** [comment]
Will do, I'll open new issues as I find them.

**Pull request merged**
